/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient.registration;

import java.awt.Color;

/**
 *
 * @author Talat
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_type = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_company = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_name2 = new javax.swing.JTextField();
        txt_name3 = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_cnic = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_relation = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_thsil = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_other = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jbox_active = new javax.swing.JCheckBox();
        jbox_died = new javax.swing.JCheckBox();
        jbox_govt = new javax.swing.JCheckBox();
        jbox_confidential = new javax.swing.JCheckBox();
        btn_Reports = new javax.swing.JButton();
        btn_PrintCard = new javax.swing.JButton();
        btn_attach = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_order = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Type");

        txt_type.setForeground(new java.awt.Color(153, 153, 153));
        txt_type.setText("Ctrl+L or F9 to LOV");
        txt_type.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_typeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_typeFocusLost(evt);
            }
        });

        jLabel3.setText("Comapny");

        txt_company.setForeground(new java.awt.Color(153, 153, 153));
        txt_company.setText("Ctrl+L or F9 to LOV");
        txt_company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_companyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_companyFocusLost(evt);
            }
        });

        jLabel4.setText("MR Num");

        jLabel5.setText("Title");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MR.", "MRS.", " " }));
        jComboBox1.setSelectedItem(this);
        jComboBox1.setEnabled(false);

        jLabel6.setText("Full Name");

        txt_name2.setForeground(new java.awt.Color(153, 153, 153));
        txt_name2.setText("ANWAR");
        txt_name2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_name2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_name2FocusLost(evt);
            }
        });

        txt_name3.setForeground(new java.awt.Color(153, 153, 153));
        txt_name3.setText("ALI");
        txt_name3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_name3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_name3FocusLost(evt);
            }
        });

        txt_Name.setForeground(new java.awt.Color(153, 153, 153));
        txt_Name.setText("Hint:Muhammad");
        txt_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NameFocusLost(evt);
            }
        });

        jLabel7.setText("Age");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year(s)" }));
        jComboBox2.setEnabled(false);

        jLabel8.setText("D.O.B");

        jComboBox3.setEnabled(false);

        jLabel9.setText("Gender");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        jComboBox4.setEnabled(false);

        jLabel10.setText("Marital Status");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "MARRIED", " " }));
        jComboBox5.setEnabled(false);

        jLabel11.setText("CNIC");

        jLabel12.setText("Contact Person");

        txt_contact.setForeground(new java.awt.Color(153, 153, 153));
        txt_contact.setText("Hint:Ali");
        txt_contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contactFocusLost(evt);
            }
        });

        jLabel13.setText("Relation");

        txt_relation.setForeground(new java.awt.Color(153, 153, 153));
        txt_relation.setText("Ctrl+L or F9 to LOV");
        txt_relation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_relationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_relationFocusLost(evt);
            }
        });

        jLabel14.setText("Tehsil");

        txt_thsil.setForeground(new java.awt.Color(153, 153, 153));
        txt_thsil.setText("Ctrl+L or F9 to LOV");
        txt_thsil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_thsilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_thsilFocusLost(evt);
            }
        });

        jLabel15.setText("Address");

        txt_address.setForeground(new java.awt.Color(153, 153, 153));
        txt_address.setText("Hint: Present Address");
        txt_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_addressFocusLost(evt);
            }
        });

        jLabel16.setText("Mobile");

        txt_mobile.setForeground(new java.awt.Color(153, 153, 153));
        txt_mobile.setText("Hint:03001111111");
        txt_mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mobileFocusLost(evt);
            }
        });

        jLabel17.setText("Other");

        txt_other.setForeground(new java.awt.Color(153, 153, 153));
        txt_other.setText("Hint:04268569893");
        txt_other.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_otherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_otherFocusLost(evt);
            }
        });

        jLabel18.setText("Email");

        txt_email.setForeground(new java.awt.Color(153, 153, 153));
        txt_email.setText("Hint:anwar@gmail.com");
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });

        jbox_active.setText("Active");
        jbox_active.setEnabled(false);

        jbox_died.setText("Died");
        jbox_died.setEnabled(false);

        jbox_govt.setText("Govt Employee");
        jbox_govt.setEnabled(false);

        jbox_confidential.setText("Confidential");
        jbox_confidential.setEnabled(false);

        btn_Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graph_report_20px.png"))); // NOI18N
        btn_Reports.setText("Reports");

        btn_PrintCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/printer_20px.png"))); // NOI18N
        btn_PrintCard.setText("Print Card");

        btn_attach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture_20px.png"))); // NOI18N
        btn_attach.setText("Attach Pic");
        btn_attach.setEnabled(false);

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_20px.png"))); // NOI18N
        btn_new.setText("New");

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_property_20px.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setEnabled(false);

        btn_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_shopping_cart_20px.png"))); // NOI18N
        btn_order.setText("Order");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_order, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbox_died)
                                .addComponent(jbox_active))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbox_govt)
                                .addComponent(jbox_confidential))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_PrintCard)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_attach, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_edit))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_mobile))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_thsil))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_cnic))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_company, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(txt_Name)
                                        .addComponent(txt_dob))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txt_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txt_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_relation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_address)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_other, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_email))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_cnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_relation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_thsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txt_other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_attach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_PrintCard)
                        .addComponent(btn_new)
                        .addComponent(btn_edit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbox_active)
                            .addComponent(jbox_govt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbox_died)
                            .addComponent(jbox_confidential))))
                .addGap(18, 18, 18)
                .addComponent(btn_order, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_typeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_typeFocusGained
        // TODO add your handling code here:
         if(txt_type.getText().equals("Ctrl+L or F9 to LOV"))
        {
            txt_type.setText("");
            txt_type.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_typeFocusGained

    private void txt_typeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_typeFocusLost
        // TODO add your handling code here:
        if(txt_type.getText().equals(""))
        {
            txt_type.setText("Ctrl+L or F9 to LOV");
            txt_type.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_typeFocusLost

    private void txt_companyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_companyFocusGained
        // TODO add your handling code here:
        if(txt_company.getText().equals("Ctrl+L or F9 to LOV"))
        {
            txt_company.setText("");
            txt_company.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_companyFocusGained

    private void txt_companyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_companyFocusLost
        // TODO add your handling code here:
        if(txt_company.getText().equals(""))
        {
            txt_company.setText("Ctrl+L or F9 to LOV");
            txt_company.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_companyFocusLost

    private void txt_name2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_name2FocusGained
        // TODO add your handling code here:
        if(txt_name2.getText().equals("ANWAR"))
        {
            txt_name2.setText("");
            txt_name2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_name2FocusGained

    private void txt_name2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_name2FocusLost
        // TODO add your handling code here:
        if(txt_name2.getText().equals(""))
        {
            txt_name2.setText("ANWAR");
            txt_name2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_name2FocusLost

    private void txt_name3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_name3FocusGained
        // TODO add your handling code here:
        if(txt_name3.getText().equals("ALI"))
        {
            txt_name3.setText("");
            txt_name3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_name3FocusGained

    private void txt_name3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_name3FocusLost
        // TODO add your handling code here:
        if(txt_name3.getText().equals(""))
        {
            txt_name3.setText("ALI");
            txt_name3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_name3FocusLost

    private void txt_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NameFocusGained
        // TODO add your handling code here:
        if(txt_Name.getText().equals("Hint:Muhammad"))
        {
            txt_Name.setText("");
            txt_Name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_NameFocusGained

    private void txt_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NameFocusLost
        // TODO add your handling code here:
        if(txt_Name.getText().equals(""))
        {
            txt_Name.setText("Hint:Muhammad");
            txt_Name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_NameFocusLost

    private void txt_contactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactFocusGained
        // TODO add your handling code here:
         if(txt_contact.getText().equals("Hint:Ali"))
        {
            txt_contact.setText("");
            txt_contact.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_txt_contactFocusGained

    private void txt_contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactFocusLost
        // TODO add your handling code here:
        if(txt_contact.getText().equals(""))
        {
            txt_contact.setText("Hint:Ali");
            txt_contact.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_contactFocusLost

    private void txt_relationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_relationFocusGained
        // TODO add your handling code here:
         if(txt_relation.getText().equals("Ctrl+L or F9 to LOV"))
        {
            txt_relation.setText("");
            txt_relation.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_relationFocusGained

    private void txt_relationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_relationFocusLost
        // TODO add your handling code here:
         if(txt_relation.getText().equals(""))
        {
            txt_relation.setText("Ctrl+L or F9 to LOV");
            txt_relation.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_relationFocusLost

    private void txt_thsilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_thsilFocusGained
        // TODO add your handling code here:
        if(txt_thsil.getText().equals("Ctrl+L or F9 to LOV"))
        {
            txt_thsil.setText("");
            txt_thsil.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_thsilFocusGained

    private void txt_thsilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_thsilFocusLost
        // TODO add your handling code here:
        if(txt_thsil.getText().equals(""))
        {
            txt_thsil.setText("Ctrl+L or F9 to LOV");
            txt_thsil.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_thsilFocusLost

    private void txt_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusGained
        // TODO add your handling code here:
        if(txt_address.getText().equals("Hint: Present Address"))
        {
            txt_address.setText("");
            txt_address.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_addressFocusGained

    private void txt_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusLost
        // TODO add your handling code here:
        if(txt_address.getText().equals(""))
        {
            txt_address.setText("Hint: Present Address");
            txt_address.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_addressFocusLost

    private void txt_mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mobileFocusGained
        // TODO add your handling code here:
       if(txt_mobile.getText().equals("Hint:03001111111"))
        {
            txt_mobile.setText("");
            txt_mobile.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_mobileFocusGained

    private void txt_mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mobileFocusLost
        // TODO add your handling code here:
         if(txt_mobile.getText().equals(""))
        {
            txt_mobile.setText("Hint:03001111111");
            txt_mobile.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_txt_mobileFocusLost

    private void txt_otherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_otherFocusGained
        // TODO add your handling code here:
         if(txt_other.getText().equals("Hint:04268569893"))
        {
            txt_other.setText("");
            txt_other.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_otherFocusGained

    private void txt_otherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_otherFocusLost
        // TODO add your handling code here:
         if(txt_other.getText().equals(""))
        {
            txt_other.setText("Hint:04268569893");
            txt_other.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_otherFocusLost

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        // TODO add your handling code here:
        if(txt_email.getText().equals("Hint:anwar@gmail.com"))
        {
            txt_email.setText("");
            txt_email.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        // TODO add your handling code here:
         if(txt_email.getText().equals(""))
        {
            txt_email.setText("Hint:anwar@gmail.com");
            txt_email.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_emailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PrintCard;
    private javax.swing.JButton btn_Reports;
    private javax.swing.JButton btn_attach;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_order;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jbox_active;
    private javax.swing.JCheckBox jbox_confidential;
    private javax.swing.JCheckBox jbox_died;
    private javax.swing.JCheckBox jbox_govt;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_cnic;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_name2;
    private javax.swing.JTextField txt_name3;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_other;
    private javax.swing.JTextField txt_relation;
    private javax.swing.JTextField txt_thsil;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables
}
